version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8011:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: task
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
      - "3337:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
